# Generated by Django 2.2.6 on 2019-10-29 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaña',
            fields=[
                ('idCam', models.AutoField(primary_key=True, serialize=False)),
                ('nomCam', models.CharField(max_length=100)),
                ('desCam', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('idCar', models.AutoField(primary_key=True, serialize=False)),
                ('nomCar', models.CharField(max_length=20)),
                ('abCar', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Dote',
            fields=[
                ('idDot', models.AutoField(primary_key=True, serialize=False)),
                ('nomDot', models.CharField(max_length=100)),
                ('desDot', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('idHab', models.AutoField(primary_key=True, serialize=False)),
                ('nomHab', models.CharField(max_length=30)),
                ('modHab', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('idPer', models.AutoField(primary_key=True, serialize=False)),
                ('nomPer', models.CharField(max_length=40)),
                ('claPer', models.CharField(max_length=20)),
                ('nivPer', models.IntegerField(verbose_name=2)),
                ('razPer', models.CharField(max_length=20)),
                ('genPer', models.CharField(max_length=10)),
                ('aliPer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rasgo',
            fields=[
                ('idRas', models.AutoField(primary_key=True, serialize=False)),
                ('valRas', models.IntegerField(verbose_name=2)),
                ('carRas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Caracteristica')),
                ('perRas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Personaje')),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('idRan', models.AutoField(primary_key=True, serialize=False)),
                ('valRan', models.IntegerField(verbose_name=2)),
                ('habRan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Habilidad')),
                ('perRan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Personaje')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgPer', models.ImageField(blank=True, upload_to='avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('idPar', models.AutoField(primary_key=True, serialize=False)),
                ('dmPar', models.BooleanField(default=False)),
                ('camPar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Campaña')),
                ('usuPar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cualidad',
            fields=[
                ('idCua', models.AutoField(primary_key=True, serialize=False)),
                ('dotCua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Dote')),
                ('perCua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Personaje')),
            ],
        ),
    ]
