# Generated by Django 3.0.2 on 2020-05-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hojapersonaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='camPar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Campaña'),
        ),
    ]
