# Generated by Django 2.2.6 on 2019-10-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hojapersonaje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cualidad',
            name='dotCua',
        ),
        migrations.AddField(
            model_name='cualidad',
            name='dotCua',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Dote'),
        ),
        migrations.RemoveField(
            model_name='cualidad',
            name='perCua',
        ),
        migrations.AddField(
            model_name='cualidad',
            name='perCua',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Personaje'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='camPar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Campaña'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='usuPar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Usuario'),
        ),
        migrations.RemoveField(
            model_name='rango',
            name='habRan',
        ),
        migrations.AddField(
            model_name='rango',
            name='habRan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Habilidad'),
        ),
        migrations.RemoveField(
            model_name='rango',
            name='perRan',
        ),
        migrations.AddField(
            model_name='rango',
            name='perRan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Personaje'),
        ),
        migrations.RemoveField(
            model_name='rasgo',
            name='carRas',
        ),
        migrations.AddField(
            model_name='rasgo',
            name='carRas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Caracteristica'),
        ),
        migrations.RemoveField(
            model_name='rasgo',
            name='perRas',
        ),
        migrations.AddField(
            model_name='rasgo',
            name='perRas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Personaje'),
        ),
    ]
