# Generated by Django 3.0.2 on 2020-01-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojapersonaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='ataPer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='fortaleza',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='reflejos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='voluntad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
