# Generated by Django 2.2.6 on 2019-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojapersonaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imgPer',
            field=models.ImageField(blank=True, upload_to='avatar/'),
        ),
    ]
