# Generated by Django 3.0.2 on 2020-04-13 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hojapersonaje', '0002_auto_20200127_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaña',
            name='usuCam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Perfil'),
        ),
    ]
