# Generated by Django 2.2.6 on 2019-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojapersonaje', '0002_auto_20191029_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imgPer',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
