# Generated by Django 3.0.2 on 2020-05-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojapersonaje', '0002_auto_20200507_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='camPer',
        ),
    ]
