# Generated by Django 3.0.2 on 2020-04-14 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hojapersonaje', '0004_remove_participa_dmpar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='usuPar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Perfil'),
        ),
    ]
