# Generated by Django 3.0.2 on 2020-04-14 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hojapersonaje', '0006_auto_20200414_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='camPar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hojapersonaje.Campaña'),
        ),
    ]
