# Generated by Django 3.0.2 on 2020-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hojapersonaje', '0007_auto_20200414_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='DGPer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='MaxDGPer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
